name = "cloudflare-imgbed"
main = "index.js"
compatibility_date = "2024-08-21"

[assets]
directory = "../../frontend-dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[[d1_databases]]
binding = "img_d1"
database_name = "img_d1"
database_id = "328a1946-293e-4fa7-bbff-4bf675bfba2c"

[[r2_buckets]]
binding = "img_r2"
bucket_name = "img"

[[routes]]
pattern = "img.fuheng.vip"
custom_domain = true
